//For Records
const FETCH_RECORD_STARTED = 'FETCH_RECORD_STARTED';
const FETCH_RECORD_SUCCESS = 'FETCH_RECORD_SUCCESS';
const FETCH_RECORD_FAIL = 'FETCH_RECORD_FAIL';
const FETCH_RECORD_API = 'FETCH_RECORD_API';
const CHANGE_BREAD = 'CHANGE_BREAD';
const FILTER_RECORD_API = 'FILTER_RECORD_API';//search api

//For Summaries
const FETCH_SUMMARIES_STARTED = 'FETCH_SUMMARIES_STARTED';
const FETCH_SUMMARIES_SUCCES = 'FETCH_SUMMARIES_SUCCES';
const FETCH_SUMMARIES_FAIL = 'FETCH_SUMMARIES_FAIL';
const FETCH_SUMMARIES_API = 'FETCH_SUMMARIES_API';

//For department
const FETCH_DEPARTMENT_API = 'FETCH_DEPARTMENT_API';
const FETCH_DEPARTMENT_SUCCES = 'FETCH_DEPARTMENT_SUCCES';
const FETCH_DEPARTMENT_FAIL = 'FETCH_DEPARTMENT_FAIL';

export {
    FETCH_RECORD_STARTED,
    FETCH_RECORD_SUCCESS,
    FETCH_RECORD_FAIL,
    FETCH_RECORD_API,
    FILTER_RECORD_API,
    CHANGE_BREAD,
    FETCH_SUMMARIES_STARTED,
    FETCH_SUMMARIES_SUCCES,
    FETCH_SUMMARIES_FAIL,
    FETCH_SUMMARIES_API,
    FETCH_DEPARTMENT_API,
    FETCH_DEPARTMENT_SUCCES,
    FETCH_DEPARTMENT_FAIL

}