const FETCH_RECORD_STARTED = 'FETCH_RECORD_STARTED';
const FETCH_RECORD_SUCCESS = 'FETCH_RECORD_SUCCESS';
const FETCH_RECORD_FAIL = 'FETCH_RECORD_FAIL';
const FETCH_RECORD_API = 'FETCH_RECORD_API';
const CHANGE_BREAD = 'CHANGE_BREAD';

export {
    FETCH_RECORD_STARTED,
    FETCH_RECORD_SUCCESS,
    FETCH_RECORD_FAIL,
    FETCH_RECORD_API,
    CHANGE_BREAD
}